grails-app/domain/melaniebangkokbackoffice/Gallery.groovy
package melaniebangkokbackoffice

class Gallery {

    String titleTh
    String titleEn
    String titleCh
    String detailTh
    String detailEn
    String detailCh
    String imageName
    Date dateCreated
    Date lastUpdated

    static hasMany = [galleryImages:GalleryImage]

    static constraints = {
        titleTh blank: false
        titleEn blank: true,nullable: true
        titleCh blank: true,nullable: true
        detailTh blank: false
        detailEn blank: true,nullable: true
        detailCh blank: true,nullable: true
        imageName blank: false
    }

    static mapping = {
        id generator: 'sequence', params: [sequence:'sequence_gallery_id']
        detailTh type: "text"
        detailEn type: "text"
        detailCh type: "text"
    }
}

grails-app/controllers/melaniebangkokbackoffice/GalleryController.groovy
package melaniebangkokbackoffice

import grails.converters.JSON

class GalleryController {

    def uploadService

    def index() {

    }

    def show() {
        def gallery = Gallery.get(params.id)
        withFormat {
            html {}
            json {
                if(params.containsKey('callback'))
                {
                    render "${params.callback}(${gallery as JSON})"
                }else{
                    render gallery as JSON
                }
            }
        }
    }

    def newForm() {
        Gallery gallery = new Gallery()
        def galleryImages = []
        [gallery:gallery,galleryImages:galleryImages]
    }

    def newImage() {
        Gallery gallery = Gallery.get(params.id)
        GalleryImage galleryImage = new GalleryImage()
        [gallery:gallery,galleryImage:galleryImage]
    }

    def editForm() {
        Gallery gallery = Gallery.get(params.id)
        def galleryImages = GalleryImage.findAllByGallery(gallery,[sort: "sequence",order:"asc"])
        [gallery:gallery,galleryImages:galleryImages]
    }

    def editImage() {
        Gallery gallery = Gallery.get(params.id)
        GalleryImage galleryImage = GalleryImage.get(params.iId)
        [gallery:gallery,galleryImage:galleryImage]
    }

    def create() {
        Gallery gallery = new Gallery(params)
        def galleryImage = []
        if (!gallery.save())
        {
            render(view: "newForm", model: [gallery: gallery,galleryImage: galleryImage])
        }else{
            if(params.containsKey('imageName') && params["imageName"] != "")
            {
                uploadService.moveFile(gallery.getImageName(),'temp','gallery')
            }
            flash.message = "Create Complete."
            redirect(action: "editForm",id: gallery.getId())
        }
    }

    def update() {
        Gallery gallery = Gallery.get(params.id)
        String oldFileName = gallery.getImageName()
        def galleryImage = gallery.getGalleryImages()
        gallery.properties = params
        if(!params.containsKey('imageName') || params["imageName"] == "")
        {
            gallery.setImageName(oldFileName)
        }
        if (!gallery.save())
        {
            flash.error = "Have Error."
            render(view: "editForm",id:params.id, model: [gallery: gallery,galleryImage: galleryImage])
        }else{
            if(params.containsKey('imageName') && params["imageName"] != "")
            {
                uploadService.deleteFile(oldFileName,'gallery')
                if(params.containsKey('imageName') && params["imageName"] != "delete")
                {
                    uploadService.moveFile(gallery.getImageName(),'temp','gallery')
                }
            }
            flash.message = "Update Complete."
            redirect(action: "editForm",id: gallery.getId())
        }
    }

    def createImage() {
        Gallery gallery = Gallery.get(params.id)
        GalleryImage galleryImage = new GalleryImage(params)
        galleryImage.setGallery(gallery)
        galleryImage.setSequence(GalleryImage.countByGallery(gallery).toInteger()+1)
        if (!galleryImage.save())
        {
            gallery.errors.allErrors.each {
                println it
            }
            flash.error = "Have Error"
            render(view: "newImage",id: params.id, model: [gallery: gallery,galleryImage:galleryImage])
        }else{
            if(params.containsKey('imageName') && params["imageName"] != "")
            {
                uploadService.moveFile(galleryImage.getImageName(),'temp','gallery')
            }
            flash.message = "Create Image Complete."
            redirect(action: "editForm",id: params.id)
        }
    }

    def updateImage() {
        if(params.containsKey('imageName') && params["imageName"] != "")
        {
            Gallery gallery = Gallery.get(params.id)
            GalleryImage galleryImage = GalleryImage.get(params.iId)
            String oldFileNameTh = galleryImage.getImageName()
            galleryImage.properties = params
            if (!galleryImage.save())
            {
                flash.error = "Have Error."
                render(view: "editImage",id:params.id,params:[iId:params.iId], model: [gallery: gallery,galleryImage: galleryImage])
            }else{
                uploadService.deleteFile(oldFileNameTh,'gallery')
                if(params.containsKey('imageName'))
                {
                    uploadService.moveFile(galleryImage.getImageName(),'temp','gallery')
                }
                flash.message = "Update Complete."
            }
        }
        redirect(action: "editForm",id:params.id)
    }

    def delete() {
        def result = [status:true]
        Gallery gallery = Gallery.get(params.id)
        if(gallery) {
            if (gallery.getGalleryImages().size() > 0) {
                result["message"] = "Have image in gallery."
                result["status"] = false
            } else {
                String fileDel = gallery.getImageName()
                result["message"] = "Delete Complete."
                if(fileDel != "")
                {
                    uploadService.deleteFile(fileDel,'gallery')
                }
                gallery.delete()
            }
        }else{
            result["message"] = "Wrong Id."
            result["status"] = false
        }
        render result as JSON
    }

    def deleteImage() {
        def result = [status:true]
        GalleryImage galleryImage = GalleryImage.get(params.id)
        if(galleryImage)
        {
            String fileDel = galleryImage.getImageName()
            galleryImage.delete()
            if(fileDel != "")
            {
                uploadService.deleteFile(fileDel,'gallery')
            }
        }else{
            result["message"] = "Wrong Image Id."
            result["status"] = false
        }
        render result as JSON
    }

    def list() {
        String sortlabel = "titleTh"
        Integer sortvalue = 1
        String searchtxt = ""
        List listColumns = ["titleTh","titleEn","titleCh"]
        if(!params.containsKey('iSortCol_0'))
        {
            params.iSortCol_0 = 0
            params.sSortDir_0 = "asc"
            params.sSearch = ""
            params.sEcho = 1
            params.iDisplayStart =0
            params.iDisplayLength = 10
        }
        if(params["iSortCol_0"].toInteger() <= (listColumns.size() - 2))
        {
            sortlabel = listColumns.getAt(params["iSortCol_0"].toInteger())
        }
        def dataList = Gallery.findAllByTitleThIlikeOrTitleEnIlikeOrTitleChIlike("%${params["sSearch"]}%","%${params["sSearch"]}%","%${params["sSearch"]}%",[max: params["iDisplayLength"].toInteger(),sort: sortlabel,order: params["sSortDir_0"],offset: params["iDisplayStart"].toInteger()])
        def totalRecord = Gallery.countByTitleThIlikeOrTitleEnIlikeOrTitleChIlike("%${params["sSearch"]}%","%${params["sSearch"]}%","%${params["sSearch"]}%")
        def sourcedatatable = [sEcho:params["sEcho"].toInteger()]
        sourcedatatable["iTotalRecords"] = totalRecord
        sourcedatatable["iTotalDisplayRecords"] = totalRecord
        List nData = []
        dataList.each {
            List iData = [it.getTitleTh(),it.getTitleEn(),it.getTitleCh(),"<a href='${createLink(action: "editForm",id: it.getId())}' class='btn btn-default'>Edit</a> <a href='javascript:void(0);' onclick=\"alertDel(${it.getId()},'${it.getTitleTh()}')\" class='btn btn-danger'>Delete</a>"]
            nData.push(iData)
        }
        sourcedatatable["aaData"] = nData
        render sourcedatatable as JSON
    }

    def saveSort(){
        def idList = params.sortList.split(",")
        def result = [status:true]
        def sortNumber = 1
        idList.each{
            GalleryImage galleryImage = GalleryImage.get(it)
            galleryImage.setSequence(sortNumber)
            galleryImage.save()
            sortNumber++
        }
        render result as JSON
    }
}

grails-app/controllers/melaniebangkokbackoffice/UploadController.groovy
package melaniebangkokbackoffice

import grails.converters.JSON
import grails.util.Holders

class UploadController {

    def uploadService

    def index() { }

    def image() {
        def result = [status:true]
        def folderPath = "temp"
        def fileName = uploadService.uploadFile(request,"Filedata[]",folderPath,"${params.module}_",params.fileType)
        if(fileName == "")
        {
            result["status"] = false
            result.put("filename","wrong file type.")
        }else{
            result.put("filename",fileName)
            result.put("pathfile",resource(dir: "uploadresource/${folderPath}/", file: fileName))
        }
        render result as JSON
    }
}

grails-app/views/gallery/_form.gsp
<div class="row">
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#th" aria-controls="th" role="tab" data-toggle="tab">Thai</a></li>
            <li role="presentation"><a href="#en" aria-controls="en" role="tab" data-toggle="tab">English</a></li>
            <li role="presentation"><a href="#ch" aria-controls="ch" role="tab" data-toggle="tab">Chinese</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="th">
                <g:render template="tabth" model="[gallery:gallery]"/>
            </div>
            <div role="tabpanel" class="tab-pane" id="en">
                <g:render template="taben" model="[gallery:gallery]"/>
            </div>
            <div role="tabpanel" class="tab-pane" id="ch">
                <g:render template="tabch" model="[gallery:gallery]"/>
            </div>
        </div>
    </div>
    <!--- File Upload --->
    <div class="form-group">
        <label for="imageName" class="col-sm-2 control-label">File Upload</label>

        <div class="col-sm-10">
            <input type="text" value="" class="form-control" style="width:200px;float:left;margin-right:10px"
                   readonly="readonly" name="imageName" id="imageName">
            <input type="button" value="Browse" onclick="showDialog()" class="btn btn-default"/>
            <p class="help-block">ขนาดรูปภาพ 1022 * 684 px</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Thumbnail</label>
        <div class="col-sm-10">
            <ul class="thumbnails">

                <g:if test="${gallery.getImageName() && gallery.getImageName() != ""}">
                    <li class="col-md-3">
                        <div class="thumbnail">
                            <a class="glyphicon glyphicon-zoom-in pull-right-margin-right" href="javascript:previewimage('<g:resource dir="uploadresource/gallery/" file="${gallery.getImageName()}"/>')"></a>
                            <a href="javascript:previewimage('<g:resource dir="uploadresource/gallery/" file="${gallery.getImageName()}"/>')">
                                <img src="<g:resource dir="uploadresource/gallery/" file="${gallery.getImageName()}"/>" class="img-thumb img-rounded"/>
                            </a>
                            <p>Current Thumbnail</p>
                        </div>
                    </li>
                </g:if>
                <li class="col-md-3" id="previewthumb">

                </li>
            </ul>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <g:if test="${params.id}">
                <a href="<g:createLink action="newImage" id="${gallery.getId()}"/> " class="btn btn-success">Add Image</a>
                <a id="saveSort" class="btn btn-primary">
                    Save Sort
                </a>
            </g:if>
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="<g:createLink action="index"/>" class="btn btn-default">Cancel</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <ul id="sortable" class="banner-item-list">
                <g:each in="${galleryImages}">
                    <li id="${it.getId()}" class="gallery-image-${it.getId()}">
                        <div class="submenu">
                            <div class="col-md-9">
                                <img src="<g:resource dir="uploadresource/gallery/" file="${it.getImageName()}"/>" class="img-thumb img-rounded col-md-4"/>
                            </div>
                            <div class="col-md-3">
                                <a href='javascript:void(0);' class='btn btn-danger pull-right' onclick="alertDel(${it.getId()},'${it.getImageName()}')">Delete</a>
                                <a href='${createLink(action: "editImage",id: gallery.getId(),params: [iId:it.getId()])}' class='btn btn-default pull-right' onclick="">Edit</a>
                            </div>
                        </div>
                    </li>
                </g:each>
            </ul>
        </div>
    </div>
</div>
<!---    Preview Thumb--->
<div class="modal fade" role="dialog" id="pModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Preview Image</h3>
            </div>
            <div class="modal-body" id="previewimage">

            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>
        </div>
    </div>
</div>
<!---    Upload--->
<div class="modal fade" tabindex="-1" role="dialog" id="bModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload Image</h4>
            </div>

            <div class="modal-body">
                <div id="resultupload"></div>

                <div id="queue"></div>
                <input id="file_upload" name="file_upload" type="file">
            </div>

            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
                <a onclick="doupload()" class="btn btn-default">Upload</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $(function () {
        $('#file_upload').uploadifive({
            'auto': false,
            'fileSizeLimit': 50000,
            'multi': false,
            'height': 25,
            'queueID': 'queue',
            'uploadScript': '<g:createLink controller="upload" action="image"/>?format=json&fileType=image&module=gallery',
            'queueSizeLimit': 1,
            'onUploadComplete': function (file, data) {
                var jsonobj = $.parseJSON(data);
                if(jsonobj.status)
                {
                    $('#resultupload').html('Upload Complete');
                    upfilecomplete(jsonobj);
                }else{
                    $('#queue').html('');
                    $('#resultupload').html('Invalid File Type');
                    $('#file_upload').uploadifive('clearQueue');
                }
            }
        });
    });

    function upfilecomplete(data) {
        $('#imageName').val(data.filename);
        $('#previewthumb').html('<a class="thumbnail"><img src="' + data.pathfile + '"/></a>');
        $("#bModal").modal('hide');
    }

    function doupload() {
        $('#file_upload').uploadifive('upload')
    }

    function showDialog() {
        $('#resultupload').html('');
        $('#file_upload').uploadifive('clearQueue');
        $("#modal-upload-iframe").html('<iframe id="modalIframeId" width="530" height="141" marginWidth="0" marginHeight="0" frameBorder="0" scrolling="no" />');
        $('#bModal').modal('show');
    }

    function previewimage(imagename)
    {
    var pathpreview = '<div class="thumbnail"><img src="'+imagename+'"/></div>';
    $('#previewimage').html(pathpreview);
        $('#pModal').modal('show');
    }
    $('#pModal').on('hidden', function () {
        $("#previewimage").html('');
    });
</script>

grails-app/views/gallery/_formImage.gsp
<!--- File Upload --->
<div class="form-group">
    <label for="imageName" class="col-sm-2 control-label">File Upload</label>

    <div class="col-sm-10">
        <input type="text" value="" class="form-control" style="width:200px;float:left;margin-right:10px"
               readonly="readonly" name="imageName" id="imageName">
        <input type="button" value="Browse" onclick="showDialog()" class="btn btn-default"/>
        <p class="help-block">ขนาดรูปภาพ 1022 * 684 px</p>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Thumbnail</label>

    <div class="col-sm-10">
        <ul class="thumbnails">

            <g:if test="${galleryImage.getImageName() && galleryImage.getImageName() != ""}">
                <li class="col-md-3">
                    <div class="thumbnail">
                        <a class="glyphicon glyphicon-zoom-in pull-right" href="javascript:previewimage('<g:resource dir="uploadresource/gallery/" file="${galleryImage.getImageName()}"/>')"></a>
                        <a href="javascript:previewimage('<g:resource dir="uploadresource/gallery/" file="${galleryImage.getImageName()}"/>')">
                            <img src="<g:resource dir="uploadresource/gallery/" file="${galleryImage.getImageName()}"/>" class="img-thumb img-rounded"/>
                        </a>
                        <p>Current Thumbnail</p>
                    </div>
                </li>
            </g:if>

            <li class="col-md-3" id="previewthumb">

            </li>
        </ul>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="<g:createLink action="editForm" id="${gallery.getId()}"/>" class="btn btn-default">Cancel</a>
    </div>
</div>
<!---    Preview Thumb--->
<div class="modal fade" role="dialog" id="pModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Preview Image</h3>
            </div>
            <div class="modal-body" id="previewimage">

            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>
        </div>
    </div>
</div>
<!---    Upload--->
<div class="modal fade" tabindex="-1" role="dialog" id="bModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload Image</h4>
            </div>

            <div class="modal-body">
                <div id="resultupload"></div>

                <div id="queue"></div>
                <input id="file_upload" name="file_upload" type="file">
            </div>

            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
                <a onclick="doupload()" class="btn btn-default">Upload</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    var fileLanguage = ""
    $(function () {
        $('#file_upload').uploadifive({
            'auto': false,
            'fileSizeLimit': 50000,
            'multi': false,
            'height': 25,
            'queueID': 'queue',
            'uploadScript': '<g:createLink controller="upload" action="image"/>?format=json&fileType=image&module=gallery',
            'queueSizeLimit': 1,
            'onUploadComplete': function (file, data) {
                var jsonobj = $.parseJSON(data);
                if(jsonobj.status)
                {
                    $('#resultupload').html('Upload Complete');
                    upfilecomplete(jsonobj);
                }else{
                    $('#queue').html('');
                    $('#resultupload').html('Invalid File Type');
                    $('#file_upload').uploadifive('clearQueue');
                }
            }
        });
    });

    function upfilecomplete(data) {
        $('#imageName').val(data.filename);
        $('#previewthumb').html('<a class="thumbnail"><img src="' + data.pathfile + '"/></a>');
        $("#bModal").modal('hide');
    }

    function doupload() {
        $('#file_upload').uploadifive('upload')
    }

    function showDialog() {
        $('#resultupload').html('');
        $('#file_upload').uploadifive('clearQueue');
        $('#bModal').modal('show');
    }
    function previewimage(imagename)
    {
        var pathpreview = '<div class="thumbnail"><img src="'+imagename+'"/></div>';
        $('#previewimage').html(pathpreview);
        $('#pModal').modal('show');
    }
    $('#pModal').on('hidden', function () {
        $("#previewimage").html('');
    });
</script>

grails-app/views/gallery/_tabch.gsp
<div class="form-group">
    <label for="inputTitleCh" class="col-sm-2 control-label">Title</label>

    <div class="col-sm-10">
        <input type="text" name="titleCh" class="form-control" id="inputTitleCh" placeholder="title"
               value="${gallery.getTitleCh()}" required>
    </div>
</div>

<div class="form-group">
    <label for="inputDetailCh" class="col-sm-2 control-label">Detail</label>

    <div class="col-sm-10">
        <textarea name="detailCh" class="form-control"
                  id="inputDetailCh">${gallery.getDetailCh() ?: ""}</textarea>
    </div>
</div>

grails-app/views/gallery/_taben.gsp
<div class="form-group">
    <label for="inputTitleEn" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <input type="text" name="titleEn" class="form-control" id="inputTitleEn" placeholder="title"
               value="${gallery.getTitleEn()}">
    </div>
</div>
<div class="form-group">
    <label for="inputDetailEn" class="col-sm-2 control-label">Detail</label>
    <div class="col-sm-10">
        <textarea name="detailEn" class="form-control"
                  id="inputDetailEn">${gallery.getDetailEn() ?: ""}</textarea>
    </div>
</div>

grails-app/views/gallery/_tabth.gsp
<div class="form-group">
    <label for="inputTitleTh" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <input type="text" name="titleTh" class="form-control" id="inputTitleTh" placeholder="title" value="${gallery.getTitleTh()}" required>
    </div>
</div>
<div class="form-group">
    <label for="inputDetailTh" class="col-sm-2 control-label">Detail</label>
    <div class="col-sm-10">
        <textarea name="detailTh" class="form-control"
                  id="inputDetailTh">${gallery.getDetailTh() ?: ""}</textarea>
    </div>
</div>

grails-app/views/gallery/editForm.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <title>Gallery : ${gallery.getTitleTh()}</title>
    <asset:stylesheet src="tabstyle.css"/>
    <asset:stylesheet src="ui-sortable.css"/>
    <asset:javascript src="jquery-ui.js"/>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/gallery">Gallery</a></li>
            <li class="active">Gallery : ${gallery.getTitleTh()}</li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1 class="no-margin-top">Gallery : ${gallery.getTitleTh()}</h1>
        </div>
    </div>
    <g:form action="update" method="POST" id="${gallery.getId()}" class="form-horizontal">
        <g:render template="form" model="['gallery':gallery,'galleryImages':galleryImages]"/>
    </g:form>
</div>
<script>
    $( function() {
        $( "#sortable" ).sortable({
            placeholder: "ui-state-highlight"
        });
        $('#saveSort').click( function(e) {
            saveSort();
            return false;
        });
    })

    function alertDel(id,message) {
        if (confirm('Are you sure you want to delete '+message+'?')) {
            $.ajax({
                url: '/gallery/deleteImage/'+id,
                method: "POST",
                dataType: "json"
            }).done(function(result){
                if(result.status)
                {
                    alert("Delete Complete.")
                    $('.gallery-image-'+id).remove()
                }else{
                    alert(result.message)
                }
            })
        }
    }

    function saveSort()
    {
        var sortList = []
        $("#sortable").find("li").each(function() {
            sortList.push($(this).attr("id"))
        })
        $.ajax({
            url: '/gallery/saveSort',
            method: "POST",
            data: { sortList : sortList.join(", ")},
            dataType: "json"
        }).done(function(result){
            if(result.status)
            {
                alert("Save Complete.")
            }
        })
    }
</script>
</body>
</html>

grails-app/views/gallery/editImage.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <title>Gallery : ${gallery.getTitleTh()}</title>
    <asset:stylesheet src="tabstyle.css"/>
    <ckeditor:resources/>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="/gallery">Gallery</a></li>
            <li><a href="<g:createLink action="editForm" id="${gallery.getId()}"/>">${gallery.getTitleTh()}</a></li>
            <li class="active">Gallery Image : Update</li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1 class="no-margin-top">Gallery : ${gallery.getTitleTh()}</h1>
        </div>
    </div>
    <g:form action="updateImage" method="POST" id="${gallery.getId()}" params="[iId:galleryImage.getId()]" class="form-horizontal">
        <g:render template="formImage" model="['gallery':gallery,'galleryImage':galleryImage]"/>
    </g:form>
</div>
</body>
</html>

grails-app/views/gallery/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <title>Gallery</title>
    %{--<asset:stylesheet src="jquery.dataTables.css"/>--}%
    <asset:stylesheet src="dataTables.bootstrap.css"/>
    <asset:javascript src="jquery.dataTables.min.js"/>
    <asset:javascript src="dataTables.bootstrap.min.js"/>
</head>
<body>
<g:if test="${flash.message}">
    <div class="alert alert-success" role="alert">
        ${flash.message}
    </div>
</g:if>
<div class="container-fluid">
    <div class="row">
        <ol class="breadcrumb">
            <li class="active">Gallery</li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h1 class="no-margin-top">Gallery</h1>
        </div>
        <div class="col-md-6">
            <a href="<g:createLink action="newForm"/>" class="btn btn-success pull-right">Create</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="example" class="table table-striped table-bordered display">
                <thead>
                <tr>
                    <th class="col-md-3">Title Th</th>
                    <th class="col-md-3">Title En</th>
                    <th class="col-md-3">Title Ch</th>
                    <th class="col-md-3">Tool</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    var oTable = '';
    $(function () {
        oTable = $('#example').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "bJQueryUI": true,
            "fnDestroy": true,
            "bRetrieve": true,
            "sPaginationType": "full_numbers",
            "sAjaxSource": "<g:createLink action="list"/>"
        });
    })

    function alertDel(id,message) {
        if (confirm('Are you sure you want to delete '+message+'?')) {
            $.ajax({
                url: '<g:createLink action="delete"/>/'+id,
                method: "POST",
                dataType: "json"
            }).done(function(result){
                if(result.status)
                {
                    alert("Delete Complete.")
                    oTable.ajax.url( '<g:createLink action="list"/>' ).load();
                }
            })
        }
    }
</script>
</body>
</html>